#!/usr/bin/env python3
"""Inline data/*.json into index.html.

The site stays a single self-contained file — that is what keeps it working in
a valley with no signal — but the catalogue is far too large to hand-maintain
inside it. So humans edit data/*.json and this script copies the result into
index.html between two markers.

    python3 tools/build.py            # inline, report what changed
    python3 tools/build.py --check    # exit 1 if index.html is stale
    python3 tools/build.py --coverage # which roadbook passes have records

Every file in data/ becomes a key on CATALOGUE named after its stem, so
dropping edges.json or places.json in there needs no change here.

Python 3 stdlib only: no package manager, in keeping with the project.
"""

import argparse
import json
import os
import re
import sys
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "index.html")
DATA = os.path.join(ROOT, "data")

BEGIN = "/* ═══ generated by tools/build.py — do not edit by hand ═══ */"
END = "/* ═══ end generated ═══ */"

# Files are inlined in this order where present; anything else in data/ follows
# alphabetically. passes first purely so the diff reads in a stable order.
ORDER = ["passes", "places", "edges"]


# ------------------------------------------------------------------ inlining

def data_files():
    if not os.path.isdir(DATA):
        return []
    found = [f for f in os.listdir(DATA) if f.endswith(".json") and not f.startswith(".")]
    return sorted(found, key=lambda f: (ORDER.index(f[:-5]) if f[:-5] in ORDER else len(ORDER), f))


def build_block():
    """The generated block, marker to marker."""
    parts, summary = [], []
    for fn in data_files():
        stem = fn[:-5]
        with open(os.path.join(DATA, fn), encoding="utf-8") as fh:
            payload = json.load(fh)
        # Compact, but one key per line would double the file; this is machine
        # output that nobody reads, so separators go as tight as JSON allows.
        blob = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        parts.append("%s:%s" % (json.dumps(stem), blob))
        n = len(payload) if isinstance(payload, (list, dict)) else 1
        summary.append((fn, n, len(blob)))
    body = "const CATALOGUE={%s};" % ",".join(parts)
    return "%s\n%s\n%s" % (BEGIN, body, END), summary


def splice(src, block):
    """Replace the generated block, or insert it just inside the main <script>."""
    if BEGIN in src:
        if END not in src:
            raise SystemExit("index.html has an opening marker but no closing one — fix by hand")
        head = src[:src.index(BEGIN)]
        tail = src[src.index(END) + len(END):]
        return head + block + tail
    # First run. The block goes at the top of the main script, before anything
    # reads it. `render('A')` runs last in that script on purpose (see
    # CLAUDE.md, "Boot order") and is unaffected by an insert at the top.
    geo = src.find("\nconst GEO")
    if geo < 0:
        raise SystemExit("could not find `const GEO` in index.html")
    tag = src.rfind("<script>", 0, geo)
    if tag < 0:
        raise SystemExit("could not find the main <script> block in index.html")
    at = src.index("\n", tag) + 1
    return src[:at] + block + "\n" + src[at:]


# ------------------------------------------------------------------ coverage

def norm(s):
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode().lower()
    s = re.sub(r"\b(passo|pass|col|colle|de|del|dello|della|di|du|le|la)\b", " ", s)
    return re.sub(r"[^a-z0-9]+", "", s)


def roadbook_passes(src):
    """The passes index.html names in PASS_SEASON, with their coarse state."""
    m = re.search(r"const PASS_SEASON\s*=\s*\{", src)
    if not m:
        return {}
    blk = src[m.start():src.index("};", m.start())]
    return dict(re.findall(r"['\"]([^'\"]+)['\"]\s*:\s*'(winter|storm|open)'", blk))


def coverage(src):
    path = os.path.join(DATA, "passes.json")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as fh:
        cat = json.load(fh)
    idx = {}
    for r in cat:
        for n in [r["name"]] + r.get("alt_names", []):
            idx.setdefault(norm(n), r["id"])
        idx.setdefault(norm(r["id"].replace("_", " ")), r["id"])
    hit, miss = [], []
    for name, state in sorted(roadbook_passes(src).items()):
        parts = [name] + re.split(r"\s*[/·]\s*", name)
        got = next((idx[norm(p)] for p in parts if norm(p) in idx), None)
        (hit if got else miss).append((name, got or state))
    return cat, hit, miss


# ---------------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if index.html does not match data/ (writes nothing)")
    ap.add_argument("--coverage", action="store_true",
                    help="report which roadbook passes have catalogue records")
    args = ap.parse_args()

    with open(INDEX, encoding="utf-8") as fh:
        src = fh.read()

    if args.coverage:
        cov = coverage(src)
        if not cov:
            raise SystemExit("data/passes.json not found")
        cat, hit, miss = cov
        total = len(hit) + len(miss)
        print("catalogue: %d records" % len(cat))
        print("roadbook passes: %d   with a record: %d   without: %d\n" % (total, len(hit), len(miss)))
        for name, rid in hit:
            print("  ok       %-34s %s" % (name, rid))
        print()
        for name, state in miss:
            print("  no rec   %-34s falls back to PASS_SEASON '%s'" % (name, state))
        return 0

    block, summary = build_block()
    if not summary:
        raise SystemExit("no .json files in data/ — nothing to inline")
    out = splice(src, block)

    if args.check:
        if out != src:
            print("index.html is STALE — run: python3 tools/build.py", file=sys.stderr)
            return 1
        print("index.html is up to date with data/")
        return 0

    if out == src:
        print("index.html already up to date (%s)" % ", ".join(f for f, _, _ in summary))
        return 0

    with open(INDEX, "w", encoding="utf-8") as fh:
        fh.write(out)
    for fn, n, size in summary:
        print("inlined %-14s %4d records  %7.1f KB" % (fn, n, size / 1024))
    print("index.html %.1f KB -> %.1f KB" % (len(src) / 1024, len(out) / 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
